### ISSUE TITLE
SideButton Component

### ISSUE THREAD

**Issue by Osama-you** [GSG-G9/Rawdaty#45]
## Acceptance Criteria
- [ ] Props
- [ ] Snapshot

---
### Props
- icon
- text
- isActive
---
### Snapshot

![image](https://user-images.githubusercontent.com/37075385/106473467-7a10b580-64ac-11eb-824b-456bc81df85f.png)
![image](https://user-images.githubusercontent.com/37075385/106473520-898ffe80-64ac-11eb-8328-058472f2d2fd.png)

**Comment by Mu7ammadAbed** [comment]
This issue will be closed because it's related to #46

**Comment by Mu7ammadAbed** [comment]
This issue will be closed because it's related to #46
