### ISSUE TITLE
SearchInput Component

### ISSUE THREAD

**Issue by alaa-sahloub** [GSG-G9/Rawdaty#47]
# SearchInput Component

## Acceptance Criteria
- [x] Props
- [x] Snapshot

---

### Props

- value

---

### Snapshot

![image](https://user-images.githubusercontent.com/44459251/106474737-e04a0800-64ad-11eb-9847-21481517e28e.png)

**Comment by Mu7ammadAbed** [comment]
This issue is related to issue #49
