### ISSUE TITLE
Loader Component

### ISSUE THREAD

**Issue by alaa-sahloub** [GSG-G9/Rawdaty#58]
# Loader Component

## Acceptance Criteria
- [ ] Snapshot
---

### Snapshot

![image](https://user-images.githubusercontent.com/44459251/106581843-fc9c8200-654b-11eb-9ef4-f156b9559bc9.png)

**Comment by Mu7ammadAbed** [comment]
Just import this component from `antd` in the common components folder and export default it 

https://ant.design/components/spin/
